### ISSUE TITLE
Error after teaching video...

### ISSUE THREAD

**Issue by pj00** [CCOMIT/CPadApp#43]
Logged in as provider (Twitter, I think), created profile with just first name, then next all the way to error.

**Comment by pj00** [comment]
There has been an error in the application

********** BEGIN EXCEPTION ********** 

Exception:
---------
CallWeka()

Source:
------
CPadApp.App

Target Site:
-----------
CallWeka

Data:
-----------
*** CurrentUser: Unknown

------------------------------
Stack Trace:
-----------
   at CPadApp.App.ControllerLogic.SurveyControllerLogic.CallWeka(GroupAbbr groupAbbr, Int32 surveyId, IPrincipal principal)
   at CPadApp.App.ControllerLogic.SurveyControllerLogic.Instructions(Int32 surveyId, String page, String instr, Int32 navDirection)
   at CPadApp.App.Controllers.SurveyController.Instructions(Int32 id, String page, String instr, Nullable`1 direction)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

********** END EXCEPTION ********** 

********** BEGIN EXCEPTION ********** 

Exception:
---------
SendSurvey()

Source:
------
CPadApp.Domain

Target Site:
-----------
SendSurvey

Data:
-----------

------------------------------
Stack Trace:
-----------
   at CPadApp.Domain.Services.CPadAppWekaService.SendSurvey(Int32 surveyId, IPrincipal principal)
   at CPadApp.App.ControllerLogic.SurveyControllerLogic.CallWeka(GroupAbbr groupAbbr, Int32 surveyId, IPrincipal principal)

********** END EXCEPTION ********** 

********** BEGIN EXCEPTION ********** 

Exception:
---------
Weka SendSurvey() failed: uuid = 7739d3a8-fa42-4cfc-8e17-7f862a8a0f38

Source:
------
CPadApp.Domain

Target Site:
-----------
SendSurvey

Data:
-----------
*** CurrentUser: test@flantech.net
********** BEGIN  Class IPrincipal: IPrincipal
********** BEGIN Claims Collection: Claims
********** BEGIN Identities Collection: Identities
   Identities [0]_AuthenticationType: ApplicationCookie
   Identities [0]_IsAuthenticated: True
   Identities [0]_Label: 
   Identities [0]_Name: test@flantech.net
   Identities [0]_NameClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
   Identities [0]_RoleClaimType: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
**********   END Identities Collection: Identities
IPrincipal_Identity: System.Security.Claims.ClaimsIdentity
********** END    Class IPrincipal: IPrincipal
surveyId: 1218

------------------------------
Stack Trace:
-----------
   at CPadApp.Domain.Services.CPadAppWekaService.SendSurvey(Int32 surveyId, IPrincipal principal)

********** END EXCEPTION ********** 

********** BEGIN EXCEPTION ********** 

Exception:
---------
SendSurvey()

Source:
------
CPadApp.Domain

Target Site:
-----------
SendSurvey

Data:
-----------
********** BEGIN  Class JsonSurvey: JsonSurvey
JsonSurvey_SurveyId: 1218
JsonSurvey_UniqueId: 7739d3a8-fa42-4cfc-8e17-7f862a8a0f38
********** END    Class JsonSurvey: JsonSurvey
WekaJsonCall: {
  "uuid": "7739d3a8-fa42-4cfc-8e17-7f862a8a0f38",
  "age": "0.0",
  "ysnQuest126": "",
  "bytQuest147": "",
  "tfQuest239": "",
  "bytQuest10": "",
  "bytQuest11": "",
  "ysnQuest131": ""
}

------------------------------
Stack Trace:
-----------
   at CPadApp.Domain.Live.EF.CPadAppRepository.SendSurvey(IJsonSurvey entity)
   at CPadApp.Domain.Services.CPadAppWekaService.SendSurvey(Int32 surveyId, IPrincipal principal)

********** END EXCEPTION ********** 

********** BEGIN EXCEPTION ********** 

Exception:
---------
The underlying connection was closed: An unexpected error occurred on a send.

Source:
------
CPadApp.Domain

Target Site:
-----------
PostRequest

Data:
-----------

------------------------------
Stack Trace:
-----------
   at CPadApp.Domain.Live.EF.CPadAppRepository.PostRequest(IJsonSurvey entity)
   at CPadApp.Domain.Live.EF.CPadAppRepository.SendSurvey(IJsonSurvey entity)

********** END EXCEPTION ********** 

********** BEGIN EXCEPTION ********** 

Exception:
---------
Authentication failed because the remote party has closed the transport stream.

Source:
------
System

Target Site:
-----------
StartReadFrame

Data:
-----------

------------------------------
Stack Trace:
-----------
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)

********** END EXCEPTION **********
